.TH rqbake 8 "Nov 21,2015" "YRMX" "YRMX System Suspend/Resume"
.SH NAME
rqbake \- unfreeze YRMX and resume operation
.SH SYNOPSIS
.fi
.B #include <ycore.h>
.sp
.BI "void rqbake(void)"
.fi
.SH DESCRIPTION
The situation existing before rqfreeze is ripristinated.
You must be a little careful with tasks in timed wait: they're frozen when they 
become running. Therefore when you unfreeze, they're activated just in order of
priority, disregarding the timing constraints.
.sp
.SH "RETURN VALUE"
None. The tasks running when rqfreeze was called are made running again.
.sp
.SH "ERRORS"
None I'm aware of.
.sp
.SH "SEE ALSO"
.BR rqfreeze (8)