.TH rqcxch 8 "Nov 21,2015" "YRMX" "YRMX Creation Functions"
.SH NAME
rqcxch \- create an exchange
.SH SYNOPSIS
.fi
.B #include <ycore.h>
.sp
.BI "void rqcxch( EXCHANGE_DESCRIPTOR *" exch " )"
.fi
.SH DESCRIPTION
The exchange structure is properly initialized for system usage.
.sp
.SH "RETURN VALUE"
None.
.sp
.SH "ERRORS"
None.
.sp
.SH "BUGS"
None I'm aware of, so far
.SH "SEE ALSO"
.BR rqdtsk (8)