.TH rqdtsk 8 "Nov 21,2015" "YRMX" "YRMX Deletion Functions"
.SH NAME
rqdtsk \- delete a task
.SH SYNOPSIS
.fi
.B #include <ycore.h>
.sp
.BI "void rqdtsk( TASK_DESCRIPTOR *" task " ) "
.fi
.SH DESCRIPTION
The task is removed from the system, and the allocated stack is
made free.
Deleting an already deleted task has no effect.
.sp
.SH "RETURN VALUE"
None.
.sp
.SH "ERRORS"
None.
.sp
.SH "BUGS"
None I'm aware of, so far.
.SH "SEE ALSO"
.BR rqctsk (8)