.TH rqdxch 8 "Nov 21,2015" "YRMX" "YRMX Deletion Functions"
.SH NAME
rqdxch \- delete an exchange
.SH SYNOPSIS
.fi
.B #include <ycore.h>
.sp
.BI "int rqdxch( EXCHANGE_DESCRIPTOR *" exch " )"
.fi
.SH DESCRIPTION
A check is performed on exchange usage. If the exchange is not
in use then the exchange is removed from the exchange list. If the exchange is in use no action is performed and zero is returned.
.sp
.SH "RETURN VALUE"
A non-zero value if the exchange has been successfully removed, zero otherwise.
.sp
.SH "ERRORS"
None.
.sp
.SH "NOTE"
An exchange cannot be safely fully deleted, because at a later time a task might attempt to send a message
or wait for a message. Therefore the exchange is just removed from the exchange list, and that's all. It's a pretty useless function which has been put there for
completeness. 
.sp
.SH "BUGS"
The name of the function is misleading.
.SH "SEE ALSO"
.BR rqcxch (8)
