.TH rqfreeze 8 "Nov 21,2015" "YRMX" "YRMX System Suspend/Resume"
.SH NAME
rqfreeze \- freeze YRMX in its current state
.SH SYNOPSIS
.fi
.B #include <ycore.h>
.sp
.BI "void rqfreeze(void)"
.fi
.SH DESCRIPTION
All YRMX interrupts are disabled, all tasks when they become running are suspended.
The current status can be analyzed with the debug functions.
It can be useful for debugging.
.br
.RB "YRMX can be reactivated (unfrozen) with " " rqbake() ".
.sp
Calling rqfreeze with YRMX already frozen has no effect.
.sp
.SH "RETURN VALUE"
None. If called from within a task different from the root task, control
doesn't return to the task unless the system is subsequently unfrozen.
.sp
.SH "ERRORS"
None.
.sp
.SH "BUGS"
None I'm aware of, so far.
.SH "SEE ALSO"
.BR rqbake (8)