.TH rqresm 8 "Nov 21,2015" "YRMX" "YRMX Suspend/Resume"
.SH NAME
rqresm \- resume a suspended task
.SH SYNOPSIS
.fi
.B #include <ycore.h>
.sp
.BI "void rqresm(TASK_DESCRIPTOR *" task " )"
.fi
.SH DESCRIPTION
If the task had been prevoulsly suspended, it is made again runnable. 
Resuming a task which was not suspended has no effect.
.sp
.SH "RETURN VALUE"
None. If the task resumed has higher priority than the calling task,
then the calling task is preemped, and the resumed task becomes
the running task.
.sp
.SH "ERRORS"
None.
.sp
.SH "BUGS"
None I'm aware of, so far.
.SH "SEE ALSO"
.BR rqsusp (8)