.TH rqstart 8 "Nov 21,2015" "YRMX" "YRMX Startup"
.SH NAME
rqstart \- Create the initial exchanges and tasks and start running
.SH SYNOPSIS
.fi
.B #include <ycore.h>
.sp
.BI "int rqstart(STD_LIST_PTR " itt[] ", int " ntask ", EXCHANGE_LIST_PTR " iet[] ");
.fi
.SH DESCRIPTION
.sp
.SH "RETURN VALUE"
.sp
.SH "ERRORS"
.sp
.SH "BUGS"
.SH "SEE ALSO"
