.TH rqsusp 8 "Nov 21,2015" "YRMX" "YRMX Suspend/Resume"
.SH NAME
rqsusp \- suspend a task
.SH SYNOPSIS
.fi
.B #include <ycore.h>
.sp
.BI "void rqsusp(TASK_DESCRIPTOR *" task " )"
.fi
.SH DESCRIPTION
If the required task is running i.e. a task suspends itself, it is suspended. 
If the required task is waiting, it is suspended as soon as it becomes runnable.
Suspending an already suspended task has no effect.
.sp
.SH "RETURN VALUE"
None. If a task supend itself, the function will return only if the
task is resumed by another task. If a task suspends another, control
returns to calling task.
.sp
.SH "ERRORS"
None.
.sp
.SH "BUGS"
None I'm aware of, so far.
.SH "SEE ALSO"
.BR rqresm (8)
